export { default as ClassDialogDistribution } from './DialogDistribution.vue'
export { default as ClassDialogCreateEdit } from './DialogCreateEdit.vue'
export { default as ClassDialogDelete } from './DialogDelete.vue'
export { default as ClassDialogAssign } from './DialogAssign.vue'
export { default as ClassDialogUpToClass } from './DialogUpToClass.vue'
